final baseUrl = "http://192.168.100.12:5000/"; // 51.91.110.63
final userUrl = 'user/';
final webUrl = "192.168.100.12:5000";
final registerUrl = baseUrl + userUrl + 'register';
final loginUrl = baseUrl + userUrl + 'login';
final userType = 'client';
final categorieUrl = baseUrl + 'categorie/';
final popularProductUrl = baseUrl + 'article/';
final articleUrl = baseUrl + 'article/';
final addToCartUrl = baseUrl + "cart/addtocart";
final myCartUrl = baseUrl + "cart/user/";
final chargeWalletUrl = baseUrl + 'wallet/recharge';
final payProductUrl = baseUrl + 'wallet/payment';
final transactionHistoryUrl = baseUrl + 'transaction/client/';
final removetoCartUrl = baseUrl + 'cart/removefromcart';
final logoutUrl = baseUrl + 'user/logout';
final newPasswordUrl = baseUrl + 'user/forgot-password';
final commandeUrl = baseUrl + 'commande/client/';
final countCategoriUrl = baseUrl + 'article/countbycategory';